package com.danielakinola.loljournal.utils;

import com.danielakinola.loljournal.R;
import com.google.common.collect.ImmutableMap;


/**
 * The ChampionGallery Class provides a mapping from each Champion's Name to their respective
 * loading screen image resource, used to visually represent them throughout the app. The HashMap
 * holding the data is statically initialized so the data is only initialized when needed. (?)
 */


public class ChampionGallery {

    public static final ImmutableMap CHAMPIONS =
            new ImmutableMap.Builder<String, Integer>()
                    .put("Aatrox", R.drawable.aatrox_loading)
                    .put("Ahri", R.drawable.ahri_loading)
                    .put("Akali", R.drawable.akali_loading)
                    .put("Alistar", R.drawable.alistar_loading)
                    .put("Amumu", R.drawable.amumu_loading)
                    .put("Anivia", R.drawable.anivia_loading)
                    .put("Annie", R.drawable.annie_loading_2)
                    .put("Ashe", R.drawable.ashe_loading)
                    .put("Aurelion Sol", R.drawable.aureliansol_loading)
                    .put("Azir", R.drawable.azir_loading)
                    .put("Bard", R.drawable.bard_loading)
                    .put("Blitzcrank", R.drawable.blitzcrank_loading)
                    .put("Brand", R.drawable.brand_loading)
                    .put("Braum", R.drawable.braum_loading)
                    .put("Caitlyn", R.drawable.caitlyn_loading)
                    .put("Camille", R.drawable.camille_loading)
                    .put("Cassiopeia", R.drawable.cassiopeia_loading)
                    .put("Cho'Gath", R.drawable.chogath_loading)
                    .put("Corki", R.drawable.corki_loading)
                    .put("Darius", R.drawable.darius_loading)
                    .put("Diana", R.drawable.diana_loading)
                    .put("Dr. Mundo", R.drawable.drmundo_loading)
                    .put("Draven", R.drawable.draven_loading)
                    .put("Ekko", R.drawable.ekko_loading)
                    .put("Elise", R.drawable.elise_loading)
                    .put("Evelynn", R.drawable.evelynn_loading)
                    .put("Ezreal", R.drawable.ezreal_loading)
                    .put("Fiddlesticks", R.drawable.fiddlesticks_loading)
                    .put("Fiora", R.drawable.fiora_loading)
                    .put("Fizz", R.drawable.fizz_loading)
                    .put("Galio", R.drawable.galio_loading)
                    .put("Gangplank", R.drawable.gangplank_loading)
                    .put("Garen", R.drawable.garen_loading)
                    .put("Gnar", R.drawable.gnar_loading)
                    .put("Gragas", R.drawable.gragas_loading)
                    .put("Graves", R.drawable.graves_loading)
                    .put("Hecarim", R.drawable.hecarim_loading)
                    .put("Heimerdinger", R.drawable.heimerdinger_loading)
                    .put("Illaoi", R.drawable.illaoi_loading)
                    .put("Irelia", R.drawable.irelia_loading)
                    .put("Ivern", R.drawable.ivern_loading)
                    .put("Janna", R.drawable.janna_loading)
                    .put("Jarvan IV", R.drawable.jarvaniv_loading)
                    .put("Jax", R.drawable.jax_loading)
                    .put("Jayce", R.drawable.jayce_loading)
                    .put("Jhin", R.drawable.jhin_loading)
                    .put("Jinx", R.drawable.jinx_loading)
                    .put("Kai'Sa", R.drawable.kaisa_loading)
                    .put("Kalista", R.drawable.kalista_loading)
                    .put("Karma", R.drawable.karma_loading)
                    .put("Karthus", R.drawable.karthus_loading)
                    .put("Kassadin", R.drawable.kassadin_loading)
                    .put("Katarina", R.drawable.katarina_loading)
                    .put("Kayn", R.drawable.kayn_loading)
                    .put("Kayle", R.drawable.kayle_loading)
                    .put("Kennen", R.drawable.kennen_loading)
                    .put("Kled", R.drawable.kled_loading)
                    .put("Kindred", R.drawable.kindred_loading)
                    .put("Kha'Zix", R.drawable.khazix_loading)
                    .put("Kog'Maw", R.drawable.kogmaw_loading)
                    .put("Leblanc", R.drawable.leblanc_loading)
                    .put("Lee Sin", R.drawable.leesin_loading)
                    .put("Leona", R.drawable.leona_loading)
                    .put("Lissandra", R.drawable.lissandra_loading)
                    .put("Lucian", R.drawable.lucian_loading)
                    .put("Lulu", R.drawable.lulu_loading)
                    .put("Lux", R.drawable.lux_loading)
                    .put("Malphite", R.drawable.malphite_loading)
                    .put("Malzahar", R.drawable.malzahar_loading)
                    .put("Maokai", R.drawable.maokai_loading)
                    .put("Master Yi", R.drawable.masteryi_loading)
                    .put("Miss Fortune", R.drawable.missfortune_loading)
                    .put("Mordekaiser", R.drawable.mordekaiser_loading)
                    .put("Morgana", R.drawable.morgana_loading)
                    .put("Nami", R.drawable.nami_loading)
                    .put("Nasus", R.drawable.nasus_loading)
                    .put("Nautilus", R.drawable.nautilus_loading)
                    .put("Nidalee", R.drawable.nidalee_loading)
                    .put("Nocturne", R.drawable.nocturne_loading)
                    .put("Nunu", R.drawable.nunu_loading)
                    .put("Olaf", R.drawable.olaf_loading)
                    .put("Orianna", R.drawable.orianna_loading)
                    .put("Ornn", R.drawable.ornn_loading)
                    .put("Pantheon", R.drawable.pantheon_loading)
                    .put("Poppy", R.drawable.poppy_loading)
                    .put("Pyke", R.drawable.pyke_loading)
                    .put("Quinn", R.drawable.quinn_loading)
                    .put("Rakan", R.drawable.rakan_loading)
                    .put("Rammus", R.drawable.rammus_loading)
                    .put("Rek'Sai", R.drawable.reksai_loading)
                    .put("Renekton", R.drawable.renekton_loading)
                    .put("Rengar", R.drawable.rengar_loading)
                    .put("Riven", R.drawable.riven_loading)
                    .put("Rumble", R.drawable.rumble_loading)
                    .put("Ryze", R.drawable.ryze_loading)
                    .put("Sejuani", R.drawable.sejuani_loading)
                    .put("Shaco", R.drawable.shaco_loading)
                    .put("Shen", R.drawable.shen_loading)
                    .put("Shyvana", R.drawable.shyvana_loading)
                    .put("Singed", R.drawable.singed_loading)
                    .put("Sion", R.drawable.sion_loading)
                    .put("Sivir", R.drawable.sivir_loading)
                    .put("Skarner", R.drawable.skarner_loading)
                    .put("Sona", R.drawable.sona_loading)
                    .put("Soraka", R.drawable.soraka_loading)
                    .put("Swain", R.drawable.swain_loading)
                    .put("Syndra", R.drawable.syndra_loading)
                    .put("Tahmkench", R.drawable.tahmkench_loading)
                    .put("Taliyah", R.drawable.taliyah_loading)
                    .put("Talon", R.drawable.talon_loading)
                    .put("Taric", R.drawable.taric_loading)
                    .put("Teemo", R.drawable.teemo_loading)
                    .put("Thresh", R.drawable.thresh_loading)
                    .put("Tristana", R.drawable.tristana_loading)
                    .put("Trundle", R.drawable.trundle_loading)
                    .put("Tryndamere", R.drawable.tryndamere_loading)
                    .put("Twisted Fate", R.drawable.twistedfate_loading)
                    .put("Twitch", R.drawable.twitch_loading)
                    .put("Udyr", R.drawable.udyr_loading)
                    .put("Urgot", R.drawable.urgot_loading)
                    .put("Varus", R.drawable.varus_loading)
                    .put("Vayne", R.drawable.vayne_loading)
                    .put("Veigar", R.drawable.veigar_loading)
                    .put("Vel'Koz", R.drawable.velkoz_loading)
                    .put("Vi", R.drawable.vi_loading)
                    .put("Viktor", R.drawable.viktor_loading)
                    .put("Vladimir", R.drawable.vladimir_loading)
                    .put("Volibear", R.drawable.volibear_loading)
                    .put("Warwick", R.drawable.warwick_loading)
                    .put("Wukong", R.drawable.wukong_loading)
                    .put("Xayah", R.drawable.xayah_loading)
                    .put("Xerath", R.drawable.xerath_loading)
                    .put("Xinzhao", R.drawable.xinzhao_loading)
                    .put("Yasuo", R.drawable.yasuo_loading)
                    .put("Yorick", R.drawable.yorick_loading)
                    .put("Zac", R.drawable.zac_loading)
                    .put("Zed", R.drawable.zed_loading)
                    .put("Ziggs", R.drawable.ziggs_loading)
                    .put("Zoe", R.drawable.zoe_loading)
                    .put("Zilean", R.drawable.zilean_loading)
                    .put("Zyra", R.drawable.zyra_loading)
                    .build();

    /* public static int getChampionImage(String champName) {
        champName = champName.toLowerCase();
        return CHAMPIONS.get(champName);
    }*/
}
